import { Poppins } from "next/font/google";
import { Roboto } from "next/font/google";
import "../config/firebase-config";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const roboto = Roboto({
	weight: ["400", "700", "900"],
	subsets: ["latin"],
	display: "swap",
});

const poppins = Poppins({
	weight: ["200", "400", "600", "800"],
	subsets: ["latin"],
	display: "swap",
});

export default function RootLayout({ children }) {
	return (
		<html lang="es" className={poppins.className}>
			<body className="h-screen w-screen">{children}</body>
		</html>
	);
}
