import { Poppins } from "next/font/google";
import { Roboto } from "next/font/google";

import Head from "next/head";
import "../config/firebase-config";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const roboto = Roboto({
	weight: ["400", "700", "900"],
	subsets: ["latin"],
	display: "swap",
});

const poppins = Poppins({
	weight: ["200", "400", "600", "800"],
	subsets: ["latin"],
	display: "swap",
});

export default function RootLayout({ children }) {
	return (
		<html lang="es" className={poppins.className}>
			<body className="h-screen w-screen">
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
					integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
					crossOrigin="anonymous"
					referrerPolicy="no-referrer"
				/>

				{children}
			</body>
		</html>
	);
}
